apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: say-something
spec:
  params:
    - name: something
      type: string
      default: "Hello World!"
  steps:
    - name: talk
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "$(params.something)"